### PR TITLE
Get all get single get multiple for search query

### LINKED ISSUE #4: GET - All , GET - Single & GET - Multiple for search query

### PR DESCRIPTION
**Pull request by faatima30**
added: 

1. quote model
2. get all
3. get by id
4. get by query search

### CODE REVIEW

**Review by sharafdin — CHANGES_REQUESTED** [review]
Thanks.
Laakiin, Waxaa jira waxyaabo qaar in aad saxdaan u baahan
1. quote-ka id giisa waa inuu noqdaa mid 1,2,3 ah ee uusan noqon mid iska sameysan.
2. marka search la sameynaayo kaliya waa in lagu search gareen karo author ka iyo oraahda ee aan lagu search gareen karin description ka.

intaan soo yara sax, inta kale waa ok. wixii ereyo, magaca file ka ah ama wixii qoral sheegta dib ayeenu ka sixi Insha'Allah!

mahdsnid markale

**Comment by faatima30** [comment]
hye engr, waan so sexeena insha Allah.

**Comment by faatima30** [comment]
> Thanks. Laakiin, Waxaa jira waxyaabo qaar in aad saxdaan u baahan
> 
> 1. quote-ka id giisa waa inuu noqdaa mid 1,2,3 ah ee uusan noqon mid iska sameysan.
> 2. marka search la sameynaayo kaliya waa in lagu search gareen karo author ka iyo oraahda ee aan lagu search gareen karin description ka.
> 
> intaan soo yara sax, inta kale waa ok. wixii ereyo, magaca file ka ah ama wixii qoral sheegta dib ayeenu ka sixi Insha'Allah!
> 
> mahdsnid markale

hye engr, waan so sexeena insha Allah.

**Comment by faatima30** [comment]
**changes we made:**

1. removed description from search.
2. changed search by query to search by author or by quote.
3. changed to 2 file names getQuotecontroller/routes to quotecontroller/routes.

**Review by sharafdin — APPROVED** [review]

**Pull request merged**
